# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ftp2Serial.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFormLayout,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QPlainTextEdit, QPushButton, QSizePolicy, QSpacerItem,
    QTabWidget, QVBoxLayout, QWidget)
import appIcon_rc

class Ui_Ftp2Serial(object):
    def setupUi(self, Ftp2Serial):
        if not Ftp2Serial.objectName():
            Ftp2Serial.setObjectName(u"Ftp2Serial")
        Ftp2Serial.resize(362, 377)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ftp2Serial.sizePolicy().hasHeightForWidth())
        Ftp2Serial.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/appIcon/icons/vga-cable.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Ftp2Serial.setWindowIcon(icon)
        self.horizontalLayout = QHBoxLayout(Ftp2Serial)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.__tabWidget = QTabWidget(Ftp2Serial)
        self.__tabWidget.setObjectName(u"__tabWidget")
#if QT_CONFIG(statustip)
        self.__tabWidget.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__tabWidget.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__tabWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.__tabWidget.setTabPosition(QTabWidget.TabPosition.West)
        self.__tabWidget.setTabShape(QTabWidget.TabShape.Triangular)
        self.__tab1 = QWidget()
        self.__tab1.setObjectName(u"__tab1")
        self.__tab1.setMinimumSize(QSize(0, 0))
        self.verticalLayout_3 = QVBoxLayout(self.__tab1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.plainTextEdit0 = QPlainTextEdit(self.__tab1)
        self.plainTextEdit0.setObjectName(u"plainTextEdit0")
        sizePolicy.setHeightForWidth(self.plainTextEdit0.sizePolicy().hasHeightForWidth())
        self.plainTextEdit0.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.plainTextEdit0)

        self.verticalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_2)

        self.buttonReadData = QPushButton(self.__tab1)
        self.buttonReadData.setObjectName(u"buttonReadData")
        sizePolicy.setHeightForWidth(self.buttonReadData.sizePolicy().hasHeightForWidth())
        self.buttonReadData.setSizePolicy(sizePolicy)
        self.buttonReadData.setMinimumSize(QSize(0, 50))

        self.verticalLayout.addWidget(self.buttonReadData)

        self.buttonSendData = QPushButton(self.__tab1)
        self.buttonSendData.setObjectName(u"buttonSendData")
        sizePolicy.setHeightForWidth(self.buttonSendData.sizePolicy().hasHeightForWidth())
        self.buttonSendData.setSizePolicy(sizePolicy)
        self.buttonSendData.setMinimumSize(QSize(0, 50))

        self.verticalLayout.addWidget(self.buttonSendData)


        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.__tabWidget.addTab(self.__tab1, "")
        self.__tabWidget.setTabText(self.__tabWidget.indexOf(self.__tab1), u"\u6570\u636e")
        self.__tab2 = QWidget()
        self.__tab2.setObjectName(u"__tab2")
        self.verticalLayout_2 = QVBoxLayout(self.__tab2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.__groupBox = QGroupBox(self.__tab2)
        self.__groupBox.setObjectName(u"__groupBox")
#if QT_CONFIG(statustip)
        self.__groupBox.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__groupBox.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__groupBox.setTitle(u"FTP \u8bbe\u7f6e")
        self.formLayout_2 = QFormLayout(self.__groupBox)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.__label_13 = QLabel(self.__groupBox)
        self.__label_13.setObjectName(u"__label_13")
        self.__label_13.setMinimumSize(QSize(50, 0))
        self.__label_13.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__label_13.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__label_13.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__label_13.setAutoFillBackground(False)
        self.__label_13.setText(u"\u5730\u5740")
        self.__label_13.setTextFormat(Qt.TextFormat.PlainText)
        self.__label_13.setScaledContents(False)
        self.__label_13.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.__label_13.setMargin(5)

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.__label_13)

        self.lineEditFtp0 = QLineEdit(self.__groupBox)
        self.lineEditFtp0.setObjectName(u"lineEditFtp0")
        sizePolicy.setHeightForWidth(self.lineEditFtp0.sizePolicy().hasHeightForWidth())
        self.lineEditFtp0.setSizePolicy(sizePolicy)
        self.lineEditFtp0.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
#if QT_CONFIG(statustip)
        self.lineEditFtp0.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lineEditFtp0.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.lineEditFtp0.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.lineEditFtp0)

        self.lineEditFtp1 = QLineEdit(self.__groupBox)
        self.lineEditFtp1.setObjectName(u"lineEditFtp1")
        sizePolicy.setHeightForWidth(self.lineEditFtp1.sizePolicy().hasHeightForWidth())
        self.lineEditFtp1.setSizePolicy(sizePolicy)
        self.lineEditFtp1.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
#if QT_CONFIG(statustip)
        self.lineEditFtp1.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lineEditFtp1.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.lineEditFtp1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.lineEditFtp1)

        self.__label_15 = QLabel(self.__groupBox)
        self.__label_15.setObjectName(u"__label_15")
        self.__label_15.setMinimumSize(QSize(50, 0))
        self.__label_15.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__label_15.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__label_15.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__label_15.setAutoFillBackground(False)
        self.__label_15.setText(u"\u5bc6\u7801")
        self.__label_15.setTextFormat(Qt.TextFormat.PlainText)
        self.__label_15.setScaledContents(False)
        self.__label_15.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.__label_15.setMargin(5)

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.__label_15)

        self.lineEditFtp2 = QLineEdit(self.__groupBox)
        self.lineEditFtp2.setObjectName(u"lineEditFtp2")
        sizePolicy.setHeightForWidth(self.lineEditFtp2.sizePolicy().hasHeightForWidth())
        self.lineEditFtp2.setSizePolicy(sizePolicy)
        self.lineEditFtp2.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
#if QT_CONFIG(statustip)
        self.lineEditFtp2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lineEditFtp2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.lineEditFtp2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.lineEditFtp2)

        self.__label_16 = QLabel(self.__groupBox)
        self.__label_16.setObjectName(u"__label_16")
        self.__label_16.setMinimumSize(QSize(50, 0))
        self.__label_16.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__label_16.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__label_16.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__label_16.setAutoFillBackground(False)
        self.__label_16.setText(u"\u8def\u5f84")
        self.__label_16.setTextFormat(Qt.TextFormat.PlainText)
        self.__label_16.setScaledContents(False)
        self.__label_16.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.__label_16.setMargin(5)

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.__label_16)

        self.lineEditFtp3 = QLineEdit(self.__groupBox)
        self.lineEditFtp3.setObjectName(u"lineEditFtp3")
        sizePolicy.setHeightForWidth(self.lineEditFtp3.sizePolicy().hasHeightForWidth())
        self.lineEditFtp3.setSizePolicy(sizePolicy)
        self.lineEditFtp3.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
#if QT_CONFIG(statustip)
        self.lineEditFtp3.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lineEditFtp3.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.lineEditFtp3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.lineEditFtp3)

        self.__label_14 = QLabel(self.__groupBox)
        self.__label_14.setObjectName(u"__label_14")
        self.__label_14.setMinimumSize(QSize(50, 0))
        self.__label_14.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__label_14.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__label_14.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__label_14.setAutoFillBackground(False)
        self.__label_14.setText(u"\u7528\u6237\u540d")
        self.__label_14.setTextFormat(Qt.TextFormat.PlainText)
        self.__label_14.setScaledContents(False)
        self.__label_14.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.__label_14.setMargin(5)

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.__label_14)


        self.verticalLayout_2.addWidget(self.__groupBox)

        self.__groupBox_2 = QGroupBox(self.__tab2)
        self.__groupBox_2.setObjectName(u"__groupBox_2")
        self.__groupBox_2.setMinimumSize(QSize(0, 0))
        self.__groupBox_2.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__groupBox_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__groupBox_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__groupBox_2.setTitle(u"\u4e32\u53e3\u8bbe\u7f6e")
        self.formLayout = QFormLayout(self.__groupBox_2)
        self.formLayout.setObjectName(u"formLayout")
        self.__label_2 = QLabel(self.__groupBox_2)
        self.__label_2.setObjectName(u"__label_2")
        self.__label_2.setMinimumSize(QSize(50, 0))
        self.__label_2.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__label_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__label_2.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__label_2.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.__label_2.setAutoFillBackground(False)
        self.__label_2.setText(u"\u4e32\u53e3\u53f7")
        self.__label_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.__label_2.setMargin(5)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.__label_2)

        self.comboBoxSerial0 = QComboBox(self.__groupBox_2)
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.addItem("")
        self.comboBoxSerial0.setObjectName(u"comboBoxSerial0")
        sizePolicy.setHeightForWidth(self.comboBoxSerial0.sizePolicy().hasHeightForWidth())
        self.comboBoxSerial0.setSizePolicy(sizePolicy)
        self.comboBoxSerial0.setMinimumSize(QSize(80, 0))
        self.comboBoxSerial0.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.comboBoxSerial0.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.comboBoxSerial0.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.comboBoxSerial0.setCurrentText(u"COM1")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.comboBoxSerial0)

        self.__label_6 = QLabel(self.__groupBox_2)
        self.__label_6.setObjectName(u"__label_6")
        self.__label_6.setMinimumSize(QSize(50, 0))
        self.__label_6.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.__label_6.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.__label_6.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.__label_6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.__label_6.setAutoFillBackground(False)
        self.__label_6.setText(u"\u6ce2\u7279\u7387")
        self.__label_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.__label_6.setMargin(5)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.__label_6)

        self.comboBoxSerial1 = QComboBox(self.__groupBox_2)
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.addItem("")
        self.comboBoxSerial1.setObjectName(u"comboBoxSerial1")
        sizePolicy.setHeightForWidth(self.comboBoxSerial1.sizePolicy().hasHeightForWidth())
        self.comboBoxSerial1.setSizePolicy(sizePolicy)
        self.comboBoxSerial1.setMinimumSize(QSize(80, 0))
        self.comboBoxSerial1.setMaximumSize(QSize(16777215, 16777215))
#if QT_CONFIG(statustip)
        self.comboBoxSerial1.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.comboBoxSerial1.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.comboBoxSerial1.setCurrentText(u"9600")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.comboBoxSerial1)


        self.verticalLayout_2.addWidget(self.__groupBox_2)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.buttonSavePara = QPushButton(self.__tab2)
        self.buttonSavePara.setObjectName(u"buttonSavePara")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.buttonSavePara.sizePolicy().hasHeightForWidth())
        self.buttonSavePara.setSizePolicy(sizePolicy1)
        self.buttonSavePara.setMinimumSize(QSize(0, 50))
        self.buttonSavePara.setFocusPolicy(Qt.FocusPolicy.NoFocus)
#if QT_CONFIG(statustip)
        self.buttonSavePara.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.buttonSavePara.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.buttonSavePara.setText(u"\u4fdd\u5b58\u53c2\u6570")

        self.verticalLayout_2.addWidget(self.buttonSavePara)

        self.__tabWidget.addTab(self.__tab2, "")
        self.__tabWidget.setTabText(self.__tabWidget.indexOf(self.__tab2), u"\u8bbe\u7f6e")

        self.horizontalLayout.addWidget(self.__tabWidget)


        self.retranslateUi(Ftp2Serial)

        self.__tabWidget.setCurrentIndex(0)
        self.comboBoxSerial0.setCurrentIndex(0)
        self.comboBoxSerial1.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Ftp2Serial)
    # setupUi

    def retranslateUi(self, Ftp2Serial):
        Ftp2Serial.setWindowTitle(QCoreApplication.translate("Ftp2Serial", u"Ftp2SerialPort", None))
        self.buttonReadData.setText(QCoreApplication.translate("Ftp2Serial", u"\u8bfb\u53d6\u6570\u636e", None))
        self.buttonSendData.setText(QCoreApplication.translate("Ftp2Serial", u"\u53d1\u9001\u6570\u636e", None))
        self.comboBoxSerial0.setItemText(0, QCoreApplication.translate("Ftp2Serial", u"COM1", None))
        self.comboBoxSerial0.setItemText(1, QCoreApplication.translate("Ftp2Serial", u"COM2", None))
        self.comboBoxSerial0.setItemText(2, QCoreApplication.translate("Ftp2Serial", u"COM3", None))
        self.comboBoxSerial0.setItemText(3, QCoreApplication.translate("Ftp2Serial", u"COM4", None))
        self.comboBoxSerial0.setItemText(4, QCoreApplication.translate("Ftp2Serial", u"COM5", None))
        self.comboBoxSerial0.setItemText(5, QCoreApplication.translate("Ftp2Serial", u"COM6", None))
        self.comboBoxSerial0.setItemText(6, QCoreApplication.translate("Ftp2Serial", u"COM7", None))
        self.comboBoxSerial0.setItemText(7, QCoreApplication.translate("Ftp2Serial", u"COM8", None))
        self.comboBoxSerial0.setItemText(8, QCoreApplication.translate("Ftp2Serial", u"COM9", None))
        self.comboBoxSerial0.setItemText(9, QCoreApplication.translate("Ftp2Serial", u"COM10", None))

        self.comboBoxSerial1.setItemText(0, QCoreApplication.translate("Ftp2Serial", u"2400", None))
        self.comboBoxSerial1.setItemText(1, QCoreApplication.translate("Ftp2Serial", u"4800", None))
        self.comboBoxSerial1.setItemText(2, QCoreApplication.translate("Ftp2Serial", u"9600", None))
        self.comboBoxSerial1.setItemText(3, QCoreApplication.translate("Ftp2Serial", u"14400", None))
        self.comboBoxSerial1.setItemText(4, QCoreApplication.translate("Ftp2Serial", u"19200", None))
        self.comboBoxSerial1.setItemText(5, QCoreApplication.translate("Ftp2Serial", u"38400", None))
        self.comboBoxSerial1.setItemText(6, QCoreApplication.translate("Ftp2Serial", u"56000", None))
        self.comboBoxSerial1.setItemText(7, QCoreApplication.translate("Ftp2Serial", u"57600", None))
        self.comboBoxSerial1.setItemText(8, QCoreApplication.translate("Ftp2Serial", u"115200", None))

    # retranslateUi

